import "./globals.css";
import { Inter } from "next/font/google";
import LandingPage from "./pages/LandingPage";
import Header from "./components/Header";

// context
import Theme from "./context/theme";
import Breakpoints from "./context/breakpoints";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Theme>
          <Breakpoints>{children}</Breakpoints>
        </Theme>
      </body>
    </html>
  );
}
